@WebAPI_HostAddress = http://localhost:5198

//Employees -------------

// All Employees
GET {{WebAPI_HostAddress}}/api/employee/
Accept: application/json

###
//Employee by ID '1'
GET {{WebAPI_HostAddress}}/api/employee/1
Accept: application/json

###
//Employee not found
GET {{WebAPI_HostAddress}}/api/employee/200
Accept: application/json

###

//Departmants -------------

// All Departmants
GET {{WebAPI_HostAddress}}/api/department/
Accept: application/json

###
//Departmant by ID '1'
GET {{WebAPI_HostAddress}}/api/department/1
Accept: application/json

###
//Departmant not found
GET {{WebAPI_HostAddress}}/api/departmant/200
Accept: application/json